//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Infrastructure.Utilities.Images
{
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    /// <remarks>
    ///   This class was auto-generated by the StronglyTypedResourceBuilder
    ///   class via a tool like ResGen or Visual Studio.
    ///   To add or remove a member, edit your .ResX file then rerun ResGen
    ///   with the /str option, or rebuild your VS project.
    /// </remarks>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceImage
    {
        // A private static field to hold the ResourceManager instance. It is used to retrieve the resources.
        private static global::System.Resources.ResourceManager resourceMan;
        // A private static field to hold the current culture information
        private static global::System.Globalization.CultureInfo resourceCulture;
        // Constructor
        // Suppresses the CA1811 warning as this private constructor is not called anywhere.
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceImage()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        /// <remarks>
        ///   Ensures that only one instance of ResourceManager is created.
        /// </remarks>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                // Check if the resource manager has already been instantiated
                if (object.ReferenceEquals(resourceMan, null))
                {
                    // Create a new ResourceManager instance specific to this class
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infrastructure.Utilities.Images.ResourceImage", typeof(ResourceImage).Assembly);
                    // Cache the ResourceManager instance for future use
                    resourceMan = temp;
                }

                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        /// <remarks>
        ///   By setting this property, you can change the culture of the resources used.
        /// </remarks>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }

            set
            {
                // Allows setting a specific CultureInfo to use for resource lookups
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        /// <remarks>
        ///   Provides a localized string for indicating success or confirmation.
        /// </remarks>
        internal static string ImageGlobalOkMessage
        {
            get
            {
                // Retrieves the localized string "ImageGlobalOkMessage" based on the current culture
                return ResourceManager.GetString("ImageGlobalOkMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The image was uploaded successfully due to an unexpected error.
        /// </summary>
        /// <remarks>
        ///   Provides a localized string for image upload success messages.
        /// </remarks>
        internal static string ImageSuccessfullyUpload
        {
            get
            {
                // Retrieves the localized string "ImageSuccessfullyUpload" based on the current culture
                return ResourceManager.GetString("ImageSuccessfullyUpload", resourceCulture);
            }
        }
    }
}