//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Infrastructure.ExternalServices.LogExternal
{
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    /// <remarks>
    ///   This class was auto-generated by the StronglyTypedResourceBuilder
    ///   class via a tool like ResGen or Visual Studio. To add or remove a member, 
    ///   edit your .ResX file then rerun ResGen with the /str option, 
    ///   or rebuild your VS project.
    /// </remarks>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceLogService
    {
        // Private static variable to hold the instance of ResourceManager
        private static global::System.Resources.ResourceManager resourceMan;
        // Private static variable to hold the CultureInfo for resource lookups
        private static global::System.Globalization.CultureInfo resourceCulture;
        /// <summary>
        ///   Constructor for ResourceLogService. This is intentionally empty as the class
        ///   serves as a container for resource accessors.
        /// </summary>
        /// <remarks>
        ///   Suppresses the warning CA1811: Avoid uncalled private code, as this constructor
        ///   may be necessary for resource initialization.
        /// </remarks>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceLogService()
        {
        }

        /// <summary>
        ///   Gets the cached ResourceManager instance used by this class for looking up resources.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    // Initialize the ResourceManager with the base name and the current assembly
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infrastructure.ExternalServices.LogExternal.ResourceLogService", typeof(ResourceLogService).Assembly);
                    resourceMan = temp;
                }

                return resourceMan;
            }
        }

        /// <summary>
        ///   Gets or sets the CultureInfo for resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }

            set
            {
                resourceCulture = value;
            }
        }

        // Below are resource strings used within this class.
        /// <summary>
        ///   Looks up a localized string similar to "The log services token got failed."
        /// </summary>
        internal static string FailedGetToken
        {
            get
            {
                return ResourceManager.GetString("FailedGetToken", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The log creation got failed."
        /// </summary>
        internal static string FailedSetLog
        {
            get
            {
                return ResourceManager.GetString("FailedSetLog", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The configuration for the log services is missing the username, password, or URL."
        /// </summary>
        internal static string FailureConfigurationMissingError
        {
            get
            {
                return ResourceManager.GetString("FailureConfigurationMissingError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "{0} was activated successfully."
        /// </summary>
        internal static string LogSuccessfullyGenericActiveated
        {
            get
            {
                return ResourceManager.GetString("LogSuccessfullyGenericActiveated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Token got successfully."
        /// </summary>
        internal static string SuccessfullyGetToken
        {
            get
            {
                return ResourceManager.GetString("SuccessfullyGetToken", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The successfully SetLog."
        /// </summary>
        internal static string SuccessfullySetLog
        {
            get
            {
                return ResourceManager.GetString("SuccessfullySetLog", resourceCulture);
            }
        }
    }
}