//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Infrastructure.Utilities.Compress
{
    using System;

    /// <summary>
    /// A strongly-typed resource class for looking up localized strings and other resources.
    /// </summary>
    /// <remarks>
    /// This class is auto-generated by the StronglyTypedResourceBuilder tool via tools like ResGen or Visual Studio.
    /// To modify resource entries, update the associated .ResX file and regenerate using the ResGen tool with the /str option or rebuild your Visual Studio project.
    /// </remarks>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceCompress
    {
        // Holds the resource manager instance used to access resource files.
        private static global::System.Resources.ResourceManager resourceMan;
        // Holds the specific culture information to be used for resource lookups.
        private static global::System.Globalization.CultureInfo resourceCulture;
        /// <summary>
        /// Initializes a new instance of the ResourceCompress class.
        /// </summary>
        /// <remarks>
        /// The constructor is empty because this class only provides static members.
        /// </remarks>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceCompress()
        {
        }

        /// <summary>
        /// Gets the cached ResourceManager instance used by this class.
        /// </summary>
        /// <remarks>
        /// The ResourceManager retrieves resources from the embedded .ResX files.
        /// It uses lazy initialization to create an instance only when necessary.
        /// </remarks>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    // Initializes the ResourceManager with the fully qualified name of the resource file.
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infrastructure.Utilities.Compress.ResourceCompress", typeof(ResourceCompress).Assembly);
                    resourceMan = temp;
                }

                return resourceMan;
            }
        }

        /// <summary>
        /// Gets or sets the CultureInfo object which selects the resource file that matches this culture.
        /// </summary>
        /// <remarks>
        /// Setting the Culture property affects all resource lookups using this class, allowing for localization.
        /// </remarks>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }

            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Looks up a localized string similar to "The image was compressed successfully."
        /// </summary>
        /// <remarks>
        /// This string can be used in the application to inform users about a successful image compression operation.
        /// It uses the ResourceManager to obtain the correct localized version of the string.
        /// </remarks>
        internal static string SuccessCompressed
        {
            get
            {
                return ResourceManager.GetString("SuccessCompressed", resourceCulture);
            }
        }
    }
}