//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Infrastructure.Repositories.Abstract.CRUD.Create
{
    using System;

    /// <summary>
    ///   A strongly-typed resource class for looking up localized strings specific to the Create operation in the CRUD process.
    /// </summary>
    /// <remarks>
    ///   This class was auto-generated by the StronglyTypedResourceBuilder
    ///   class using tools like ResGen or Visual Studio.
    ///   If you need to add or modify members, alter the related .ResX file and rerun ResGen
    ///   with the /str option, or simply rebuild your Visual Studio project.
    /// </remarks>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()] // Indicates that the method calls of this class will be skipped in the debugging process.
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()] // Indicates to the compiler that this class was automatically generated.
    internal class ResourceCreateRepository
    {
        // Holds a static reference to the singleton instance of the ResourceManager
        private static global::System.Resources.ResourceManager resourceMan;
        // Stores the CultureInfo which will be used for resource lookups.
        private static global::System.Globalization.CultureInfo resourceCulture;
        /// <summary>
        ///   Constructor for the ResourceCreateRepository class that suppresses CA1811: AvoidUncalledPrivateCode.
        ///   Made private to prevent instantiation since this class is only used for retrieving resources.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceCreateRepository()
        {
        }

        /// <summary>
        ///   Provides access to the cached ResourceManager instance used by this class.
        ///   This property ensures that the ResourceManager is instantiated only once, achieving efficient resource management.
        /// </summary>
        /// <returns>A ResourceManager instance for handling resource strings.</returns>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)] // Marks the property as intended for advanced use, hiding it from general browsing scenarios in code completion tools.
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    // Lazy initialization of the ResourceManager, ensuring thread-safe access.
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infrastructure.Repositories.Abstract.CRUD.Create.ResourceCreateRepository", typeof(ResourceCreateRepository).Assembly);
                    resourceMan = temp;
                }

                return resourceMan;
            }
        }

        /// <summary>
        ///   Gets or sets the CultureInfo to be used for resource lookups,
        ///   allowing overriding of the current UI culture thread setting.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }

            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Retrieves a localized string with a placeholder that represents the creation of an entity,
        ///   such as "{0} was created successfully.".
        ///   The placeholder {0} can be replaced with a specific entity name or type for more context.
        /// </summary>
        internal static string SuccessfullyGeneric
        {
            get
            {
                return ResourceManager.GetString("SuccessfullyGeneric", resourceCulture);
            }
        }
    }
}