//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Infrastructure.Repositories.Implementation.CRUD.User.Update
{
    using System;

    /// <summary>
    ///   A strongly-typed resource class for looking up localized strings related to user update operations.
    /// </summary>
    /// <remarks>
    ///   This class is auto-generated by the StronglyTypedResourceBuilder tool like ResGen or Visual Studio.
    ///   To modify the resources, update the respective .resx file and regenerate this class using the tool.
    /// </remarks>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceUpdate
    {
        // The ResourceManager instance used to manage localized resources
        private static global::System.Resources.ResourceManager resourceMan;
        // The CultureInfo instance used for resource culture-specific lookups
        private static global::System.Globalization.CultureInfo resourceCulture;
        /// <summary>
        ///   Constructor for ResourceUpdate class.
        /// </summary>
        /// <remarks>
        ///   This is a private constructor to prevent direct instantiation.
        /// </remarks>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceUpdate()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        /// <remarks>
        ///   It creates the instance if it doesn't already exist.
        /// </remarks>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infrastructure.Repositories.Implementation.CRUD.User.Update.ResourceUpdate", typeof(ResourceUpdate).Assembly);
                    resourceMan = temp;
                }

                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        /// <remarks>
        ///   Utilized for managing culture-specific resource strings.
        /// </remarks>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }

            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Retrieves a localized string indicating that an email is already registered.
        /// </summary>
        internal static string UpdateFailedAlreadyRegisteredEmail
        {
            get
            {
                return ResourceManager.GetString("UpdateFailedAlreadyRegisteredEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Retrieves a localized string indicating the submission of user data with size or format errors.
        /// </summary>
        internal static string UpdateFailedDataSizeCharacter
        {
            get
            {
                return ResourceManager.GetString("UpdateFailedDataSizeCharacter", resourceCulture);
            }
        }

        /// <summary>
        ///   Retrieves a localized string indicating an invalid email format error.
        /// </summary>
        internal static string UpdateFailedEmailInvalidFormat
        {
            get
            {
                return ResourceManager.GetString("UpdateFailedEmailInvalidFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Retrieves a localized string indicating a successful search operation in a generic entity.
        /// </summary>
        internal static string UpdateSuccessfullySearchGeneric
        {
            get
            {
                return ResourceManager.GetString("UpdateSuccessfullySearchGeneric", resourceCulture);
            }
        }
    }
}