//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Infrastructure.Repositories.Abstract.Status
{
    using System;

    /// <summary>
    ///   A strongly-typed resource class for looking up localized strings.
    ///   This class is useful for obtaining culture-specific resources at runtime,
    ///   such as error messages or UI text.
    /// </summary>
    /// <remarks>
    ///   This class was auto-generated by the StronglyTypedResourceBuilder
    ///   class via a tool like ResGen or Visual Studio.
    ///   To add or remove a member, edit your .ResX file then rerun ResGen
    ///   with the /str option, or rebuild your Visual Studio project.
    /// </remarks>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceStatusRepository
    {
        // A static field to hold the resource manager instance for this class.
        private static global::System.Resources.ResourceManager resourceMan;
        // A static field to hold the culture information for resource localization.
        private static global::System.Globalization.CultureInfo resourceCulture;
        /// <summary>
        ///   Constructor for the ResourceStatusRepository class.
        ///   Currently, it does not perform any specific initialization.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceStatusRepository()
        {
        }

        /// <summary>
        ///   Provides access to the ResourceManager instance used by this class.
        ///   The ResourceManager is responsible for retrieving resources based on culture.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                // Instantiate the ResourceManager if it has not been already.
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infrastructure.Repositories.Abstract.Status.ResourceStatusRepository", typeof(ResourceStatusRepository).Assembly);
                    resourceMan = temp;
                }

                return resourceMan;
            }
        }

        /// <summary>
        ///   Gets or sets the culture used for resource lookups.
        ///   Changing this culture alters the language of retrieved resources.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }

            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Retrieves a localized string indicating necessary data was not provided.
        ///   This message might be used for error handling or logging.
        /// </summary>
        internal static string StatusFailedNecesaryData
        {
            get
            {
                return ResourceManager.GetString("StatusFailedNecesaryData", resourceCulture);
            }
        }

        /// <summary>
        ///   Retrieves a localized string indicating a global success status ('Ok').
        ///   This message might be used to confirm successful operations.
        /// </summary>
        internal static string StatusGlobalOkMessage
        {
            get
            {
                return ResourceManager.GetString("StatusGlobalOkMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Retrieves a localized string for indicating a successful disabling action.
        ///   The message includes a placeholder for the name of the disabled item.
        /// </summary>
        internal static string StatusSuccessfullyGenericDisabled
        {
            get
            {
                return ResourceManager.GetString("StatusSuccessfullyGenericDisabled", resourceCulture);
            }
        }
    }
}