//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Infrastructure.Repositories.Abstract.CRUD.Validation
{
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    /// <remarks>
    /// This class was auto-generated by the StronglyTypedResourceBuilder
    /// class via a tool like ResGen or Visual Studio. To add or remove a member,
    /// edit your .ResX file then rerun ResGen with the /str option, or rebuild
    /// your VS project.
    /// </remarks>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceValidation
    {
        // Static fields for caching the ResourceManager and CultureInfo objects used by this class
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;
        // Constructor marked with SuppressMessageAttribute to indicate that it is not used.
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceValidation()
        {
        }

        /// <summary>
        ///   Provides a cached instance of ResourceManager for accessing resources.
        /// </summary>
        /// <returns>Returns the cached ResourceManager instance used by this class.</returns>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                // Initialize the ResourceManager if it hasn't been instantiated yet.
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infrastructure.Repositories.Abstract.CRUD.Validation.ResourceValidation", typeof(ResourceValidation).Assembly);
                    resourceMan = temp;
                }

                return resourceMan;
            }
        }

        /// <summary>
        ///   Gets or sets the CultureInfo object for resource lookups.
        /// </summary>
        /// <remarks>
        /// Overrides the current thread's CurrentUICulture property for all resource lookups using this strongly typed resource class.
        /// </remarks>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }

            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Locates a localized string similar to "Necessary data was not provided."
        /// </summary>
        /// <returns>Returns the localized string associated with "FailedNecesaryData".</returns>
        internal static string FailedNecesaryData
        {
            get
            {
                // Fetches and returns the localized string for "FailedNecesaryData".
                return ResourceManager.GetString("FailedNecesaryData", resourceCulture);
            }
        }

        /// <summary>
        ///   Locates a localized string similar to "The {0} does not exist."
        /// </summary>
        /// <returns>Returns the localized string associated with "GenericExistValidation".</returns>
        internal static string GenericExistValidation
        {
            get
            {
                // Fetches and returns the localized string for "GenericExistValidation".
                return ResourceManager.GetString("GenericExistValidation", resourceCulture);
            }
        }

        /// <summary>
        ///   Locates a localized string similar to "Ok."
        /// </summary>
        /// <returns>Returns the localized string associated with "ValidationGlobalOkMessage".</returns>
        internal static string ValidationGlobalOkMessage
        {
            get
            {
                // Fetches and returns the localized string for "ValidationGlobalOkMessage".
                return ResourceManager.GetString("ValidationGlobalOkMessage", resourceCulture);
            }
        }
    }
}